// Static mock data for running without Supabase.
// The tables object is mutated in place so other modules can keep a stable reference.

const TENANT_ID = "t1";
const USER_ID = "u1";

function isoDate(offsetDays = 0) {
  const date = new Date(Date.now() + offsetDays * 86400000);
  return date.toISOString().split("T")[0];
}

function isoTimestamp(offsetDays = 0, hour = 10, minute = 0) {
  const date = new Date(Date.now() + offsetDays * 86400000);
  date.setUTCHours(hour, minute, 0, 0);
  return date.toISOString();
}

function buildMockTables() {
  const tenants = [
    {
      id: TENANT_ID,
      business_name: "AquaPure Services",
      owner_name: "Kaushal Patil",
      phone: "9876543210",
      email: "kaushal@aquapure.com",
      address: "Office 204, Baner Business Hub, Pune",
      logo_url: null,
      subscription_status: "active",
      created_at: isoTimestamp(-120),
    },
  ];

  const users = [
    {
      id: USER_ID,
      tenant_id: TENANT_ID,
      name: "Kaushal Patil",
      phone: "9876543210",
      role: "owner",
      created_at: isoTimestamp(-120),
    },
  ];

  const customers = [
    {
      id: "c1",
      tenant_id: TENANT_ID,
      name: "Rajesh Kumar",
      phone: "9876500001",
      email: "rajesh@gmail.com",
      address: "123 MG Road, Pune",
      city: "Pune",
      purifier_brand: "Kent",
      purifier_model: "Grand Plus",
      installation_date: isoDate(-290),
      notes: "AMC customer. Prefers morning visits.",
      created_at: isoTimestamp(-290),
    },
    {
      id: "c2",
      tenant_id: TENANT_ID,
      name: "Priya Sharma",
      phone: "9876500002",
      email: "priya@gmail.com",
      address: "456 FC Road, Pune",
      city: "Pune",
      purifier_brand: "Aquaguard",
      purifier_model: "Enhance RO+UV",
      installation_date: isoDate(-240),
      notes: "Water flow issue repeats every few months.",
      created_at: isoTimestamp(-240),
    },
    {
      id: "c3",
      tenant_id: TENANT_ID,
      name: "Amit Deshmukh",
      phone: "9876500003",
      email: "amit@gmail.com",
      address: "789 JM Road, Mumbai",
      city: "Mumbai",
      purifier_brand: "Pureit",
      purifier_model: "Ultima Mineral",
      installation_date: isoDate(-225),
      notes: "Corporate client referral.",
      created_at: isoTimestamp(-225),
    },
    {
      id: "c4",
      tenant_id: TENANT_ID,
      name: "Sneha Joshi",
      phone: "9876500004",
      email: "sneha@gmail.com",
      address: "12 Shivaji Nagar, Pune",
      city: "Pune",
      purifier_brand: "Kent",
      purifier_model: "Pearl",
      installation_date: isoDate(-200),
      notes: "Needs prior call before technician arrival.",
      created_at: isoTimestamp(-200),
    },
    {
      id: "c5",
      tenant_id: TENANT_ID,
      name: "Vikram Patel",
      phone: "9876500005",
      email: "vikram@gmail.com",
      address: "88 Baner Road, Pune",
      city: "Pune",
      purifier_brand: "Aquaguard",
      purifier_model: "Aura",
      installation_date: isoDate(-160),
      notes: "Cash payer. Keeps physical invoices.",
      created_at: isoTimestamp(-160),
    },
    {
      id: "c6",
      tenant_id: TENANT_ID,
      name: "Neha Kulkarni",
      phone: "9876500006",
      email: "neha@gmail.com",
      address: "22 Kothrud Depot, Pune",
      city: "Pune",
      purifier_brand: "AO Smith",
      purifier_model: "Z9 Hot+Cold",
      installation_date: isoDate(-145),
      notes: "Premium annual maintenance contract.",
      created_at: isoTimestamp(-145),
    },
    {
      id: "c7",
      tenant_id: TENANT_ID,
      name: "Suresh Pawar",
      phone: "9876500007",
      email: "suresh@gmail.com",
      address: "14 Model Colony, Pune",
      city: "Pune",
      purifier_brand: "Livpure",
      purifier_model: "Bolt+ Copper",
      installation_date: isoDate(-130),
      notes: "Asked for next service reminder 2 days early.",
      created_at: isoTimestamp(-130),
    },
    {
      id: "c8",
      tenant_id: TENANT_ID,
      name: "Anita More",
      phone: "9876500008",
      email: "anita@gmail.com",
      address: "502 Aundh Heights, Pune",
      city: "Pune",
      purifier_brand: "Pureit",
      purifier_model: "Eco Water Saver",
      installation_date: isoDate(-95),
      notes: "Referred by Rajesh Kumar.",
      created_at: isoTimestamp(-95),
    },
    {
      id: "c9",
      tenant_id: TENANT_ID,
      name: "Rohan Nair",
      phone: "9876500009",
      email: "rohan@gmail.com",
      address: "91 Powai Lake View, Mumbai",
      city: "Mumbai",
      purifier_brand: "Kent",
      purifier_model: "Excell Plus",
      installation_date: isoDate(-80),
      notes: "Apartment access only after 11 AM.",
      created_at: isoTimestamp(-80),
    },
    {
      id: "c10",
      tenant_id: TENANT_ID,
      name: "Pooja Shah",
      phone: "9876500010",
      email: "pooja@gmail.com",
      address: "7 Koregaon Park Lane 4, Pune",
      city: "Pune",
      purifier_brand: "Aquaguard",
      purifier_model: "Marvel NXT",
      installation_date: isoDate(-60),
      notes: "Requested invoice on email and WhatsApp.",
      created_at: isoTimestamp(-60),
    },
  ];

  const customerLookup = Object.fromEntries(
    customers.map((customer) => [customer.id, customer])
  );

  function customerJoin(customerId) {
    const customer = customerLookup[customerId];
    return {
      name: customer.name,
      phone: customer.phone,
      address: customer.address,
      purifier_model: customer.purifier_model,
      purifier_brand: customer.purifier_brand,
    };
  }

  const services = [
    {
      id: "s1",
      tenant_id: TENANT_ID,
      customer_id: "c1",
      service_type: "maintenance",
      status: "completed",
      scheduled_date: isoDate(-35),
      completed_date: isoDate(-35),
      next_due_date: isoDate(18),
      next_contact_date: isoDate(16),
      assigned_to: USER_ID,
      amount: 650,
      service_charge: 250,
      parts_replaced: [
        { name: "Sediment Filter", quantity: 1, cost: 180 },
        { name: "Carbon Filter", quantity: 1, cost: 220 },
      ],
      notes: "Completed successfully. Suggested AMC renewal next month.",
      created_at: isoTimestamp(-35),
      customers: customerJoin("c1"),
    },
    {
      id: "s2",
      tenant_id: TENANT_ID,
      customer_id: "c2",
      service_type: "repair",
      status: "pending",
      scheduled_date: isoDate(0),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(1),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Customer reported low water flow and pump noise.",
      created_at: isoTimestamp(-6),
      customers: customerJoin("c2"),
    },
    {
      id: "s3",
      tenant_id: TENANT_ID,
      customer_id: "c3",
      service_type: "installation",
      status: "scheduled",
      scheduled_date: isoDate(1),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(1),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Fresh installation for office pantry unit.",
      created_at: isoTimestamp(-4),
      customers: customerJoin("c3"),
    },
    {
      id: "s4",
      tenant_id: TENANT_ID,
      customer_id: "c4",
      service_type: "maintenance",
      status: "scheduled",
      scheduled_date: isoDate(4),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(3),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Routine 6-month preventive maintenance.",
      created_at: isoTimestamp(-3),
      customers: customerJoin("c4"),
    },
    {
      id: "s5",
      tenant_id: TENANT_ID,
      customer_id: "c1",
      service_type: "maintenance",
      status: "scheduled",
      scheduled_date: isoDate(-3),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(-2),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Overdue filter replacement visit.",
      created_at: isoTimestamp(-10),
      customers: customerJoin("c1"),
    },
    {
      id: "s6",
      tenant_id: TENANT_ID,
      customer_id: "c5",
      service_type: "repair",
      status: "completed",
      scheduled_date: isoDate(-9),
      completed_date: isoDate(-9),
      next_due_date: null,
      next_contact_date: null,
      assigned_to: USER_ID,
      amount: 900,
      service_charge: 300,
      parts_replaced: [
        { name: "Solenoid Valve", quantity: 1, cost: 600 },
      ],
      notes: "Leakage fixed near input valve.",
      created_at: isoTimestamp(-9),
      customers: customerJoin("c5"),
    },
    {
      id: "s7",
      tenant_id: TENANT_ID,
      customer_id: "c6",
      service_type: "maintenance",
      status: "followup",
      scheduled_date: isoDate(-1),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(2),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "TDS still high. Follow-up visit required after membrane flush.",
      created_at: isoTimestamp(-8),
      customers: customerJoin("c6"),
    },
    {
      id: "s8",
      tenant_id: TENANT_ID,
      customer_id: "c7",
      service_type: "inspection",
      status: "rejected",
      scheduled_date: isoDate(-7),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(3),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Customer postponed service until next salary cycle.",
      created_at: isoTimestamp(-7),
      customers: customerJoin("c7"),
    },
    {
      id: "s9",
      tenant_id: TENANT_ID,
      customer_id: "c8",
      service_type: "repair",
      status: "scheduled",
      scheduled_date: isoDate(0),
      completed_date: null,
      next_due_date: null,
      next_contact_date: isoDate(0),
      assigned_to: USER_ID,
      amount: 0,
      service_charge: 0,
      parts_replaced: [],
      notes: "Power supply issue. Bring spare SMPS.",
      created_at: isoTimestamp(-2),
      customers: customerJoin("c8"),
    },
    {
      id: "s10",
      tenant_id: TENANT_ID,
      customer_id: "c9",
      service_type: "maintenance",
      status: "completed",
      scheduled_date: isoDate(-18),
      completed_date: isoDate(-18),
      next_due_date: isoDate(25),
      next_contact_date: isoDate(23),
      assigned_to: USER_ID,
      amount: 1250,
      service_charge: 350,
      parts_replaced: [
        { name: "RO Membrane", quantity: 1, cost: 650 },
        { name: "Pre Filter", quantity: 1, cost: 250 },
      ],
      notes: "Major preventive maintenance completed.",
      created_at: isoTimestamp(-18),
      customers: customerJoin("c9"),
    },
    {
      id: "s11",
      tenant_id: TENANT_ID,
      customer_id: "c10",
      service_type: "installation",
      status: "completed",
      scheduled_date: isoDate(-28),
      completed_date: isoDate(-28),
      next_due_date: isoDate(60),
      next_contact_date: isoDate(58),
      assigned_to: USER_ID,
      amount: 1800,
      service_charge: 500,
      parts_replaced: [
        { name: "Installation Kit", quantity: 1, cost: 1300 },
      ],
      notes: "New system installed and demo given.",
      created_at: isoTimestamp(-28),
      customers: customerJoin("c10"),
    },
    {
      id: "s12",
      tenant_id: TENANT_ID,
      customer_id: "c2",
      service_type: "maintenance",
      status: "completed",
      scheduled_date: isoDate(-58),
      completed_date: isoDate(-58),
      next_due_date: isoDate(-2),
      next_contact_date: isoDate(-3),
      assigned_to: USER_ID,
      amount: 700,
      service_charge: 250,
      parts_replaced: [
        { name: "UV Lamp", quantity: 1, cost: 450 },
      ],
      notes: "Earlier preventive maintenance for repeat service history.",
      created_at: isoTimestamp(-58),
      customers: customerJoin("c2"),
    },
  ];

  const bills = [
    {
      id: "b1",
      tenant_id: TENANT_ID,
      customer_id: "c1",
      service_id: "s1",
      bill_number: "BILL-20260301-0001",
      amount: 650,
      tax: 0,
      total: 650,
      payment_status: "paid",
      payment_method: "upi",
      paid_date: isoDate(-35),
      created_at: isoTimestamp(-35),
      customers: customerJoin("c1"),
    },
    {
      id: "b2",
      tenant_id: TENANT_ID,
      customer_id: "c5",
      service_id: "s6",
      bill_number: "BILL-20260327-0002",
      amount: 900,
      tax: 0,
      total: 900,
      payment_status: "paid",
      payment_method: "cash",
      paid_date: isoDate(-9),
      created_at: isoTimestamp(-9),
      customers: customerJoin("c5"),
    },
    {
      id: "b3",
      tenant_id: TENANT_ID,
      customer_id: "c2",
      service_id: "s2",
      bill_number: "BILL-20260403-0003",
      amount: 350,
      tax: 0,
      total: 350,
      payment_status: "unpaid",
      payment_method: null,
      paid_date: null,
      created_at: isoTimestamp(0),
      customers: customerJoin("c2"),
    },
    {
      id: "b4",
      tenant_id: TENANT_ID,
      customer_id: "c9",
      service_id: "s10",
      bill_number: "BILL-20260318-0004",
      amount: 1250,
      tax: 0,
      total: 1250,
      payment_status: "paid",
      payment_method: "card",
      paid_date: isoDate(-18),
      created_at: isoTimestamp(-18),
      customers: customerJoin("c9"),
    },
    {
      id: "b5",
      tenant_id: TENANT_ID,
      customer_id: "c10",
      service_id: "s11",
      bill_number: "BILL-20260308-0005",
      amount: 1800,
      tax: 0,
      total: 1800,
      payment_status: "paid",
      payment_method: "bank_transfer",
      paid_date: isoDate(-28),
      created_at: isoTimestamp(-28),
      customers: customerJoin("c10"),
    },
    {
      id: "b6",
      tenant_id: TENANT_ID,
      customer_id: "c6",
      service_id: "s7",
      bill_number: "BILL-20260402-0006",
      amount: 450,
      tax: 0,
      total: 450,
      payment_status: "unpaid",
      payment_method: null,
      paid_date: null,
      created_at: isoTimestamp(-1),
      customers: customerJoin("c6"),
    },
  ];

  const bill_items = [
    { id: "bi1", bill_id: "b1", description: "Service Charge - maintenance", quantity: 1, unit_price: 250, total: 250 },
    { id: "bi2", bill_id: "b1", description: "Sediment Filter", quantity: 1, unit_price: 180, total: 180 },
    { id: "bi3", bill_id: "b1", description: "Carbon Filter", quantity: 1, unit_price: 220, total: 220 },
    { id: "bi4", bill_id: "b2", description: "Service Charge - repair", quantity: 1, unit_price: 300, total: 300 },
    { id: "bi5", bill_id: "b2", description: "Solenoid Valve", quantity: 1, unit_price: 600, total: 600 },
    { id: "bi6", bill_id: "b3", description: "Inspection Fee", quantity: 1, unit_price: 150, total: 150 },
    { id: "bi7", bill_id: "b3", description: "Estimated minor repair", quantity: 1, unit_price: 200, total: 200 },
    { id: "bi8", bill_id: "b4", description: "Service Charge - maintenance", quantity: 1, unit_price: 350, total: 350 },
    { id: "bi9", bill_id: "b4", description: "RO Membrane", quantity: 1, unit_price: 650, total: 650 },
    { id: "bi10", bill_id: "b4", description: "Pre Filter", quantity: 1, unit_price: 250, total: 250 },
    { id: "bi11", bill_id: "b5", description: "Installation Charge", quantity: 1, unit_price: 500, total: 500 },
    { id: "bi12", bill_id: "b5", description: "Installation Kit", quantity: 1, unit_price: 1300, total: 1300 },
    { id: "bi13", bill_id: "b6", description: "Follow-up visit charge", quantity: 1, unit_price: 450, total: 450 },
  ];

  const notifications = [
    {
      id: "n1",
      tenant_id: TENANT_ID,
      customer_id: "c1",
      service_id: "s5",
      type: "service_due",
      title: "Overdue service reminder",
      body: "Rajesh Kumar has an overdue maintenance visit pending.",
      sent_at: isoTimestamp(-2, 4, 30),
      status: "sent",
    },
    {
      id: "n2",
      tenant_id: TENANT_ID,
      customer_id: "c6",
      service_id: "s7",
      type: "followup",
      title: "Follow-up required",
      body: "Neha Kulkarni needs a TDS follow-up visit in two days.",
      sent_at: isoTimestamp(-1, 6, 0),
      status: "sent",
    },
    {
      id: "n3",
      tenant_id: TENANT_ID,
      customer_id: "c10",
      service_id: "s11",
      type: "payment",
      title: "Invoice paid",
      body: "Pooja Shah completed payment for installation invoice.",
      sent_at: isoTimestamp(-27, 8, 15),
      status: "sent",
    },
  ];

  return {
    tenants,
    users,
    customers,
    services,
    bills,
    bill_items,
    notifications,
  };
}

const tables = {};

function resetMockTables() {
  const freshTables = buildMockTables();

  for (const key of Object.keys(tables)) {
    delete tables[key];
  }

  for (const [key, value] of Object.entries(freshTables)) {
    tables[key] = value;
  }

  return freshTables;
}

function getMockSummary() {
  return {
    tenants: tables.tenants.length,
    users: tables.users.length,
    customers: tables.customers.length,
    services: tables.services.length,
    bills: tables.bills.length,
    bill_items: tables.bill_items.length,
    notifications: tables.notifications.length,
  };
}

resetMockTables();

module.exports = {
  TENANT_ID,
  USER_ID,
  tables,
  resetMockTables,
  getMockSummary,
};
