// Static mock data for running without Supabase
const TENANT_ID = "t1";
const USER_ID = "u1";

const tenants = [
  {
    id: TENANT_ID,
    business_name: "AquaPure Services",
    owner_name: "Kaushal Patil",
    phone: "9876543210",
    email: "kaushal@aquapure.com",
    subscription_status: "active",
    created_at: "2025-01-15T10:00:00Z",
  },
];

const users = [
  {
    id: USER_ID,
    tenant_id: TENANT_ID,
    name: "Kaushal Patil",
    phone: "9876543210",
    role: "owner",
    created_at: "2025-01-15T10:00:00Z",
  },
];

const customers = [
  {
    id: "c1",
    tenant_id: TENANT_ID,
    name: "Rajesh Kumar",
    phone: "9876500001",
    email: "rajesh@gmail.com",
    address: "123 MG Road, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Grand Plus",
    installation_date: "2024-06-15",
    created_at: "2024-06-15T10:00:00Z",
  },
  {
    id: "c2",
    tenant_id: TENANT_ID,
    name: "Priya Sharma",
    phone: "9876500002",
    email: "priya@gmail.com",
    address: "456 FC Road, Pune",
    city: "Pune",
    purifier_brand: "Aquaguard",
    purifier_model: "Enhance",
    installation_date: "2024-08-20",
    created_at: "2024-08-20T10:00:00Z",
  },
  {
    id: "c3",
    tenant_id: TENANT_ID,
    name: "Amit Deshmukh",
    phone: "9876500003",
    email: "amit@gmail.com",
    address: "789 JM Road, Mumbai",
    city: "Mumbai",
    purifier_brand: "Pureit",
    purifier_model: "Ultima",
    installation_date: "2024-09-10",
    created_at: "2024-09-10T10:00:00Z",
  },
  {
    id: "c4",
    tenant_id: TENANT_ID,
    name: "Sneha Joshi",
    phone: "9876500004",
    email: "sneha@gmail.com",
    address: "12 Shivaji Nagar, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Pearl",
    installation_date: "2024-10-05",
    created_at: "2024-10-05T10:00:00Z",
  },
  {
    id: "c5",
    tenant_id: TENANT_ID,
    name: "Vikram Patel",
    phone: "9876500005",
    email: "vikram@gmail.com",
    address: "88 Baner Road, Pune",
    city: "Pune",
    purifier_brand: "Aquaguard",
    purifier_model: "Aura",
    installation_date: "2025-01-12",
    created_at: "2025-01-12T10:00:00Z",
  },
];

const today = new Date().toISOString().split("T")[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split("T")[0];
const nextWeek = new Date(Date.now() + 5 * 86400000).toISOString().split("T")[0];
const lastWeek = new Date(Date.now() - 5 * 86400000).toISOString().split("T")[0];
const lastMonth = new Date(Date.now() - 20 * 86400000).toISOString().split("T")[0];

const services = [
  {
    id: "s1",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_type: "maintenance",
    status: "completed",
    scheduled_date: lastMonth,
    completed_date: lastMonth,
    next_due_date: nextWeek,
    amount: 500,
    notes: "Replaced filter cartridge",
    assigned_to: USER_ID,
    created_at: "2025-01-20T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "s2",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_type: "repair",
    status: "pending",
    scheduled_date: today,
    completed_date: null,
    next_due_date: null,
    amount: null,
    notes: "Water flow issue reported",
    assigned_to: USER_ID,
    created_at: "2025-02-10T10:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
  {
    id: "s3",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_type: "installation",
    status: "upcoming",
    scheduled_date: tomorrow,
    completed_date: null,
    next_due_date: null,
    amount: null,
    notes: "New installation",
    assigned_to: USER_ID,
    created_at: "2025-02-15T10:00:00Z",
    customers: { name: "Amit Deshmukh", phone: "9876500003", address: "789 JM Road, Mumbai" },
  },
  {
    id: "s4",
    tenant_id: TENANT_ID,
    customer_id: "c4",
    service_type: "maintenance",
    status: "upcoming",
    scheduled_date: nextWeek,
    completed_date: null,
    next_due_date: null,
    amount: null,
    notes: "Routine 6-month maintenance",
    assigned_to: USER_ID,
    created_at: "2025-02-18T10:00:00Z",
    customers: { name: "Sneha Joshi", phone: "9876500004", address: "12 Shivaji Nagar, Pune" },
  },
  {
    id: "s5",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_type: "maintenance",
    status: "upcoming",
    scheduled_date: lastWeek,
    completed_date: null,
    next_due_date: null,
    amount: null,
    notes: "Overdue - filter replacement",
    assigned_to: USER_ID,
    created_at: "2025-02-20T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "s6",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_type: "repair",
    status: "completed",
    scheduled_date: lastWeek,
    completed_date: lastWeek,
    next_due_date: null,
    amount: 800,
    notes: "Fixed leaking valve",
    assigned_to: USER_ID,
    created_at: "2025-02-22T10:00:00Z",
    customers: { name: "Vikram Patel", phone: "9876500005", address: "88 Baner Road, Pune" },
  },
];

const bills = [
  {
    id: "b1",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_id: "s1",
    bill_number: "BILL-20250120-0001",
    amount: 500,
    tax: 90,
    total: 590,
    payment_status: "paid",
    payment_method: "upi",
    paid_date: lastMonth,
    created_at: "2025-01-20T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "b2",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_id: "s6",
    bill_number: "BILL-20250222-0002",
    amount: 800,
    tax: 144,
    total: 944,
    payment_status: "paid",
    payment_method: "cash",
    paid_date: lastWeek,
    created_at: "2025-02-22T10:00:00Z",
    customers: { name: "Vikram Patel", phone: "9876500005", address: "88 Baner Road, Pune" },
  },
  {
    id: "b3",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_id: "s2",
    bill_number: "BILL-20250210-0003",
    amount: 350,
    tax: 63,
    total: 413,
    payment_status: "unpaid",
    payment_method: null,
    paid_date: null,
    created_at: "2025-02-10T10:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
];

const bill_items = [
  { id: "bi1", bill_id: "b1", description: "Filter Cartridge Replacement", quantity: 1, unit_price: 350, total: 350 },
  { id: "bi2", bill_id: "b1", description: "Service Charge", quantity: 1, unit_price: 150, total: 150 },
  { id: "bi3", bill_id: "b2", description: "Valve Replacement", quantity: 1, unit_price: 500, total: 500 },
  { id: "bi4", bill_id: "b2", description: "Labour Charge", quantity: 1, unit_price: 300, total: 300 },
  { id: "bi5", bill_id: "b3", description: "Inspection Fee", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi6", bill_id: "b3", description: "Minor Repair", quantity: 1, unit_price: 150, total: 150 },
];

const notifications = [];

module.exports = {
  TENANT_ID,
  USER_ID,
  tables: {
    tenants,
    users,
    customers,
    services,
    bills,
    bill_items,
    notifications,
  },
};
