// Static mock data for running without Supabase
const TENANT_ID = "t1";
const USER_ID = "u1";

const tenants = [
  {
    id: TENANT_ID,
    business_name: "AquaPure Services",
    owner_name: "Kaushal Patil",
    phone: "9876543210",
    email: "kaushal@aquapure.com",
    address: "Shop 12, MG Road, Pune 411001",
    logo_url: null,
    subscription_status: "active",
    created_at: "2025-01-15T10:00:00Z",
  },
];

const users = [
  {
    id: USER_ID,
    tenant_id: TENANT_ID,
    name: "Kaushal Patil",
    phone: "9876543210",
    role: "owner",
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "u2",
    tenant_id: TENANT_ID,
    name: "Rahul Mehta",
    phone: "9876543211",
    role: "technician",
    created_at: "2025-02-01T10:00:00Z",
  },
  {
    id: "u3",
    tenant_id: TENANT_ID,
    name: "Sunil Yadav",
    phone: "9876543212",
    role: "technician",
    created_at: "2025-03-01T10:00:00Z",
  },
];

const customers = [
  {
    id: "c1",
    tenant_id: TENANT_ID,
    name: "Rajesh Kumar",
    phone: "9876500001",
    email: "rajesh@gmail.com",
    address: "123 MG Road, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Grand Plus",
    installation_date: "2024-06-15",
    notes: "Preferred time: morning 9-11 AM",
    created_at: "2024-06-15T10:00:00Z",
  },
  {
    id: "c2",
    tenant_id: TENANT_ID,
    name: "Priya Sharma",
    phone: "9876500002",
    email: "priya@gmail.com",
    address: "456 FC Road, Pune",
    city: "Pune",
    purifier_brand: "Aquaguard",
    purifier_model: "Enhance",
    installation_date: "2024-08-20",
    notes: "Has a dog, call before visiting",
    created_at: "2024-08-20T10:00:00Z",
  },
  {
    id: "c3",
    tenant_id: TENANT_ID,
    name: "Amit Deshmukh",
    phone: "9876500003",
    email: "amit@gmail.com",
    address: "789 JM Road, Mumbai",
    city: "Mumbai",
    purifier_brand: "Pureit",
    purifier_model: "Ultima",
    installation_date: "2024-09-10",
    notes: null,
    created_at: "2024-09-10T10:00:00Z",
  },
  {
    id: "c4",
    tenant_id: TENANT_ID,
    name: "Sneha Joshi",
    phone: "9876500004",
    email: "sneha@gmail.com",
    address: "12 Shivaji Nagar, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Pearl",
    installation_date: "2024-10-05",
    notes: "AMC customer - priority service",
    created_at: "2024-10-05T10:00:00Z",
  },
  {
    id: "c5",
    tenant_id: TENANT_ID,
    name: "Vikram Patel",
    phone: "9876500005",
    email: "vikram@gmail.com",
    address: "88 Baner Road, Pune",
    city: "Pune",
    purifier_brand: "Aquaguard",
    purifier_model: "Aura",
    installation_date: "2025-01-12",
    notes: null,
    created_at: "2025-01-12T10:00:00Z",
  },
  {
    id: "c6",
    tenant_id: TENANT_ID,
    name: "Meena Kulkarni",
    phone: "9876500006",
    email: "meena.kulkarni@yahoo.com",
    address: "34 Deccan Gymkhana, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Supreme Lite",
    installation_date: "2024-04-22",
    notes: "Elderly customer, be patient",
    created_at: "2024-04-22T10:00:00Z",
  },
  {
    id: "c7",
    tenant_id: TENANT_ID,
    name: "Sanjay Gupta",
    phone: "9876500007",
    email: "sanjay.g@gmail.com",
    address: "56 Andheri West, Mumbai",
    city: "Mumbai",
    purifier_brand: "Livpure",
    purifier_model: "Glo Star",
    installation_date: "2024-11-18",
    notes: null,
    created_at: "2024-11-18T10:00:00Z",
  },
  {
    id: "c8",
    tenant_id: TENANT_ID,
    name: "Neha Reddy",
    phone: "9876500008",
    email: "neha.reddy@outlook.com",
    address: "90 Koregaon Park, Pune",
    city: "Pune",
    purifier_brand: "Aquaguard",
    purifier_model: "Magna NXT",
    installation_date: "2025-02-05",
    notes: "New customer referred by Priya Sharma",
    created_at: "2025-02-05T10:00:00Z",
  },
  {
    id: "c9",
    tenant_id: TENANT_ID,
    name: "Rohit Deshpande",
    phone: "9876500009",
    email: "rohit.d@gmail.com",
    address: "23 Viman Nagar, Pune",
    city: "Pune",
    purifier_brand: "Pureit",
    purifier_model: "Copper+ Mineral",
    installation_date: "2024-07-30",
    notes: "Office installation - contact receptionist first",
    created_at: "2024-07-30T10:00:00Z",
  },
  {
    id: "c10",
    tenant_id: TENANT_ID,
    name: "Anjali Thakur",
    phone: "9876500010",
    email: "anjali.t@gmail.com",
    address: "67 Wakad, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Gold Optima",
    installation_date: "2025-03-10",
    notes: "Recently installed - first service due in 6 months",
    created_at: "2025-03-10T10:00:00Z",
  },
  {
    id: "c11",
    tenant_id: TENANT_ID,
    name: "Deepak Nair",
    phone: "9876500011",
    email: "deepak.nair@gmail.com",
    address: "45 Dadar East, Mumbai",
    city: "Mumbai",
    purifier_brand: "Livpure",
    purifier_model: "Bolt+ Copper",
    installation_date: "2024-12-01",
    notes: null,
    created_at: "2024-12-01T10:00:00Z",
  },
  {
    id: "c12",
    tenant_id: TENANT_ID,
    name: "Kavita Bhosle",
    phone: "9876500012",
    email: "kavita.b@gmail.com",
    address: "11 Hinjewadi Phase 1, Pune",
    city: "Pune",
    purifier_brand: "Pureit",
    purifier_model: "Classic Nxt",
    installation_date: "2024-05-14",
    notes: "Frequent complaint caller",
    created_at: "2024-05-14T10:00:00Z",
  },
  {
    id: "c13",
    tenant_id: TENANT_ID,
    name: "Manish Tiwari",
    phone: "9876500013",
    email: "manish.t@gmail.com",
    address: "78 Thane West, Mumbai",
    city: "Mumbai",
    purifier_brand: "Aquaguard",
    purifier_model: "Ritz",
    installation_date: "2025-01-25",
    notes: null,
    created_at: "2025-01-25T10:00:00Z",
  },
  {
    id: "c14",
    tenant_id: TENANT_ID,
    name: "Pooja Sawant",
    phone: "9876500014",
    email: "pooja.s@gmail.com",
    address: "32 Kothrud, Pune",
    city: "Pune",
    purifier_brand: "Kent",
    purifier_model: "Ace Extra",
    installation_date: "2024-03-08",
    notes: "AMC renewed in Jan 2025",
    created_at: "2024-03-08T10:00:00Z",
  },
  {
    id: "c15",
    tenant_id: TENANT_ID,
    name: "Arjun Mane",
    phone: "9876500015",
    email: "arjun.mane@gmail.com",
    address: "99 Hadapsar, Pune",
    city: "Pune",
    purifier_brand: "Livpure",
    purifier_model: "Zinger",
    installation_date: "2025-03-20",
    notes: "New installation - warranty till March 2026",
    created_at: "2025-03-20T10:00:00Z",
  },
];

// Dynamic date helpers
const today = new Date().toISOString().split("T")[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split("T")[0];
const dayAfterTomorrow = new Date(Date.now() + 2 * 86400000).toISOString().split("T")[0];
const threeDaysLater = new Date(Date.now() + 3 * 86400000).toISOString().split("T")[0];
const nextWeek = new Date(Date.now() + 5 * 86400000).toISOString().split("T")[0];
const twoWeeksLater = new Date(Date.now() + 14 * 86400000).toISOString().split("T")[0];
const lastWeek = new Date(Date.now() - 5 * 86400000).toISOString().split("T")[0];
const twoDaysAgo = new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0];
const threeDaysAgo = new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0];
const lastMonth = new Date(Date.now() - 20 * 86400000).toISOString().split("T")[0];
const twoMonthsAgo = new Date(Date.now() - 55 * 86400000).toISOString().split("T")[0];
const threeMonthsAgo = new Date(Date.now() - 85 * 86400000).toISOString().split("T")[0];
const sixMonthsLater = new Date(Date.now() + 180 * 86400000).toISOString().split("T")[0];
const threeMonthsLater = new Date(Date.now() + 90 * 86400000).toISOString().split("T")[0];
const fourMonthsLater = new Date(Date.now() + 120 * 86400000).toISOString().split("T")[0];
const oneMonthLater = new Date(Date.now() + 30 * 86400000).toISOString().split("T")[0];

const services = [
  // ===== COMPLETED SERVICES (history) =====
  {
    id: "s1",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_type: "installation",
    status: "completed",
    scheduled_date: "2024-06-15",
    completed_date: "2024-06-15",
    next_due_date: "2024-12-15",
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: 1500,
    service_charge: 500,
    parts_replaced: [{ name: "Installation Kit", quantity: 1, cost: 1000 }],
    notes: "New Kent Grand Plus installation with standard kit",
    created_at: "2024-06-15T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "s2",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_type: "maintenance",
    status: "completed",
    scheduled_date: "2024-12-15",
    completed_date: "2024-12-16",
    next_due_date: sixMonthsLater,
    next_contact_date: null,
    assigned_to: "u2",
    amount: 650,
    service_charge: 200,
    parts_replaced: [
      { name: "Sediment Filter", quantity: 1, cost: 250 },
      { name: "Carbon Filter", quantity: 1, cost: 200 },
    ],
    notes: "6-month maintenance - replaced sediment and carbon filters",
    created_at: "2024-12-10T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "s3",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_type: "installation",
    status: "completed",
    scheduled_date: "2024-08-20",
    completed_date: "2024-08-20",
    next_due_date: "2025-02-20",
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: 1200,
    service_charge: 400,
    parts_replaced: [{ name: "Installation Kit", quantity: 1, cost: 800 }],
    notes: "Aquaguard Enhance installation at FC Road",
    created_at: "2024-08-20T10:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
  {
    id: "s4",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_type: "installation",
    status: "completed",
    scheduled_date: "2024-09-10",
    completed_date: "2024-09-10",
    next_due_date: "2025-03-10",
    next_contact_date: null,
    assigned_to: "u2",
    amount: 1100,
    service_charge: 400,
    parts_replaced: [{ name: "Installation Kit", quantity: 1, cost: 700 }],
    notes: "Pureit Ultima installation in Mumbai",
    created_at: "2024-09-10T10:00:00Z",
    customers: { name: "Amit Deshmukh", phone: "9876500003", address: "789 JM Road, Mumbai" },
  },
  {
    id: "s5",
    tenant_id: TENANT_ID,
    customer_id: "c6",
    service_type: "filter_change",
    status: "completed",
    scheduled_date: twoMonthsAgo,
    completed_date: twoMonthsAgo,
    next_due_date: fourMonthsLater,
    next_contact_date: null,
    assigned_to: "u3",
    amount: 900,
    service_charge: 200,
    parts_replaced: [
      { name: "RO Membrane", quantity: 1, cost: 500 },
      { name: "Sediment Filter", quantity: 1, cost: 200 },
    ],
    notes: "Annual RO membrane + sediment filter change for Meena ji",
    created_at: twoMonthsAgo + "T10:00:00Z",
    customers: { name: "Meena Kulkarni", phone: "9876500006", address: "34 Deccan Gymkhana, Pune" },
  },
  {
    id: "s6",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_type: "repair",
    status: "completed",
    scheduled_date: lastWeek,
    completed_date: lastWeek,
    next_due_date: null,
    next_contact_date: oneMonthLater,
    assigned_to: USER_ID,
    amount: 800,
    service_charge: 300,
    parts_replaced: [{ name: "Inlet Valve", quantity: 1, cost: 500 }],
    notes: "Fixed leaking inlet valve, customer asked to check again in 1 month",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Vikram Patel", phone: "9876500005", address: "88 Baner Road, Pune" },
  },
  {
    id: "s7",
    tenant_id: TENANT_ID,
    customer_id: "c9",
    service_type: "amc",
    status: "completed",
    scheduled_date: lastMonth,
    completed_date: lastMonth,
    next_due_date: threeMonthsLater,
    next_contact_date: null,
    assigned_to: "u2",
    amount: 450,
    service_charge: 200,
    parts_replaced: [{ name: "Pre-Filter Candle", quantity: 2, cost: 250 }],
    notes: "Quarterly AMC service - office unit running well",
    created_at: lastMonth + "T10:00:00Z",
    customers: { name: "Rohit Deshpande", phone: "9876500009", address: "23 Viman Nagar, Pune" },
  },
  {
    id: "s8",
    tenant_id: TENANT_ID,
    customer_id: "c12",
    service_type: "repair",
    status: "completed",
    scheduled_date: threeMonthsAgo,
    completed_date: threeMonthsAgo,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u3",
    amount: 1200,
    service_charge: 300,
    parts_replaced: [
      { name: "UV Lamp", quantity: 1, cost: 600 },
      { name: "SMPS Board", quantity: 1, cost: 300 },
    ],
    notes: "UV lamp failure and SMPS board replaced. Customer was upset about delay.",
    created_at: threeMonthsAgo + "T10:00:00Z",
    customers: { name: "Kavita Bhosle", phone: "9876500012", address: "11 Hinjewadi Phase 1, Pune" },
  },
  {
    id: "s9",
    tenant_id: TENANT_ID,
    customer_id: "c7",
    service_type: "general_service",
    status: "completed",
    scheduled_date: lastMonth,
    completed_date: lastMonth,
    next_due_date: sixMonthsLater,
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: 350,
    service_charge: 350,
    parts_replaced: [],
    notes: "General checkup and sanitization, no parts needed",
    created_at: lastMonth + "T10:00:00Z",
    customers: { name: "Sanjay Gupta", phone: "9876500007", address: "56 Andheri West, Mumbai" },
  },
  {
    id: "s10",
    tenant_id: TENANT_ID,
    customer_id: "c14",
    service_type: "amc",
    status: "completed",
    scheduled_date: twoDaysAgo,
    completed_date: twoDaysAgo,
    next_due_date: threeMonthsLater,
    next_contact_date: null,
    assigned_to: "u2",
    amount: 550,
    service_charge: 200,
    parts_replaced: [
      { name: "Sediment Filter", quantity: 1, cost: 150 },
      { name: "Carbon Block", quantity: 1, cost: 200 },
    ],
    notes: "Quarterly AMC service done. All readings normal.",
    created_at: twoDaysAgo + "T10:00:00Z",
    customers: { name: "Pooja Sawant", phone: "9876500014", address: "32 Kothrud, Pune" },
  },
  {
    id: "s11",
    tenant_id: TENANT_ID,
    customer_id: "c11",
    service_type: "filter_change",
    status: "completed",
    scheduled_date: threeDaysAgo,
    completed_date: threeDaysAgo,
    next_due_date: sixMonthsLater,
    next_contact_date: null,
    assigned_to: "u3",
    amount: 750,
    service_charge: 150,
    parts_replaced: [
      { name: "Sediment Filter", quantity: 1, cost: 200 },
      { name: "Carbon Filter", quantity: 1, cost: 200 },
      { name: "UF Membrane", quantity: 1, cost: 200 },
    ],
    notes: "Full filter change for Livpure unit",
    created_at: threeDaysAgo + "T10:00:00Z",
    customers: { name: "Deepak Nair", phone: "9876500011", address: "45 Dadar East, Mumbai" },
  },

  // ===== TODAY'S SERVICES =====
  {
    id: "s12",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_type: "repair",
    status: "pending",
    scheduled_date: today,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Water flow reduced significantly, customer says TDS is high",
    created_at: threeDaysAgo + "T10:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
  {
    id: "s13",
    tenant_id: TENANT_ID,
    customer_id: "c12",
    service_type: "general_service",
    status: "pending",
    scheduled_date: today,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u2",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Customer requested general checkup after recent repair",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Kavita Bhosle", phone: "9876500012", address: "11 Hinjewadi Phase 1, Pune" },
  },
  {
    id: "s14",
    tenant_id: TENANT_ID,
    customer_id: "c8",
    service_type: "maintenance",
    status: "pending",
    scheduled_date: today,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u3",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "First maintenance after installation",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Neha Reddy", phone: "9876500008", address: "90 Koregaon Park, Pune" },
  },

  // ===== UPCOMING SERVICES (next 7 days) =====
  {
    id: "s15",
    tenant_id: TENANT_ID,
    customer_id: "c4",
    service_type: "amc",
    status: "scheduled",
    scheduled_date: tomorrow,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Quarterly AMC visit - priority customer",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Sneha Joshi", phone: "9876500004", address: "12 Shivaji Nagar, Pune" },
  },
  {
    id: "s16",
    tenant_id: TENANT_ID,
    customer_id: "c10",
    service_type: "maintenance",
    status: "scheduled",
    scheduled_date: tomorrow,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u2",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "First maintenance check after new installation",
    created_at: twoDaysAgo + "T10:00:00Z",
    customers: { name: "Anjali Thakur", phone: "9876500010", address: "67 Wakad, Pune" },
  },
  {
    id: "s17",
    tenant_id: TENANT_ID,
    customer_id: "c13",
    service_type: "installation",
    status: "scheduled",
    scheduled_date: dayAfterTomorrow,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u3",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "New Aquaguard Ritz installation - customer upgrading from old unit",
    created_at: today + "T10:00:00Z",
    customers: { name: "Manish Tiwari", phone: "9876500013", address: "78 Thane West, Mumbai" },
  },
  {
    id: "s18",
    tenant_id: TENANT_ID,
    customer_id: "c15",
    service_type: "maintenance",
    status: "scheduled",
    scheduled_date: threeDaysLater,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Post-installation checkup",
    created_at: today + "T10:00:00Z",
    customers: { name: "Arjun Mane", phone: "9876500015", address: "99 Hadapsar, Pune" },
  },
  {
    id: "s19",
    tenant_id: TENANT_ID,
    customer_id: "c6",
    service_type: "filter_change",
    status: "scheduled",
    scheduled_date: nextWeek,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u2",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Scheduled filter change - carbon + sediment",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Meena Kulkarni", phone: "9876500006", address: "34 Deccan Gymkhana, Pune" },
  },

  // ===== OVERDUE / DUE SERVICES =====
  {
    id: "s20",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_type: "maintenance",
    status: "scheduled",
    scheduled_date: lastWeek,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: USER_ID,
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "OVERDUE - 6 month maintenance, customer not picking calls",
    created_at: lastMonth + "T10:00:00Z",
    customers: { name: "Amit Deshmukh", phone: "9876500003", address: "789 JM Road, Mumbai" },
  },
  {
    id: "s21",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_type: "filter_change",
    status: "scheduled",
    scheduled_date: threeDaysAgo,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u3",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "OVERDUE - RO membrane replacement due",
    created_at: lastMonth + "T10:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },

  // ===== FOLLOW-UP SERVICES =====
  {
    id: "s22",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_type: "repair",
    status: "followup",
    scheduled_date: nextWeek,
    completed_date: null,
    next_due_date: null,
    next_contact_date: nextWeek,
    assigned_to: USER_ID,
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Follow-up on inlet valve repair - check if leak resolved",
    created_at: lastWeek + "T10:00:00Z",
    customers: { name: "Vikram Patel", phone: "9876500005", address: "88 Baner Road, Pune" },
  },
  {
    id: "s23",
    tenant_id: TENANT_ID,
    customer_id: "c12",
    service_type: "repair",
    status: "followup",
    scheduled_date: twoWeeksLater,
    completed_date: null,
    next_due_date: null,
    next_contact_date: twoWeeksLater,
    assigned_to: "u3",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Follow-up on UV lamp + SMPS board replacement - monitor performance",
    created_at: threeDaysAgo + "T10:00:00Z",
    customers: { name: "Kavita Bhosle", phone: "9876500012", address: "11 Hinjewadi Phase 1, Pune" },
  },

  // ===== REJECTED SERVICE =====
  {
    id: "s24",
    tenant_id: TENANT_ID,
    customer_id: "c9",
    service_type: "repair",
    status: "rejected",
    scheduled_date: lastMonth,
    completed_date: null,
    next_due_date: null,
    next_contact_date: null,
    assigned_to: "u2",
    amount: null,
    service_charge: null,
    parts_replaced: null,
    notes: "Customer rejected repair - said cost too high, will buy new unit instead",
    created_at: lastMonth + "T10:00:00Z",
    customers: { name: "Rohit Deshpande", phone: "9876500009", address: "23 Viman Nagar, Pune" },
  },
];

const bills = [
  // ===== PAID BILLS - various payment methods =====
  {
    id: "b1",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_id: "s1",
    bill_number: "BILL-20240615-0001",
    amount: 1500,
    tax: 270,
    total: 1770,
    payment_status: "paid",
    payment_method: "upi",
    paid_date: "2024-06-15",
    created_at: "2024-06-15T12:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "b2",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_id: "s2",
    bill_number: "BILL-20241216-0002",
    amount: 650,
    tax: 117,
    total: 767,
    payment_status: "paid",
    payment_method: "cash",
    paid_date: "2024-12-16",
    created_at: "2024-12-16T12:00:00Z",
    customers: { name: "Rajesh Kumar", phone: "9876500001", address: "123 MG Road, Pune" },
  },
  {
    id: "b3",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_id: "s3",
    bill_number: "BILL-20240820-0003",
    amount: 1200,
    tax: 216,
    total: 1416,
    payment_status: "paid",
    payment_method: "online",
    paid_date: "2024-08-22",
    created_at: "2024-08-20T12:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
  {
    id: "b4",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_id: "s4",
    bill_number: "BILL-20240910-0004",
    amount: 1100,
    tax: 198,
    total: 1298,
    payment_status: "paid",
    payment_method: "upi",
    paid_date: "2024-09-10",
    created_at: "2024-09-10T12:00:00Z",
    customers: { name: "Amit Deshmukh", phone: "9876500003", address: "789 JM Road, Mumbai" },
  },
  {
    id: "b5",
    tenant_id: TENANT_ID,
    customer_id: "c6",
    service_id: "s5",
    bill_number: "BILL-20250205-0005",
    amount: 900,
    tax: 162,
    total: 1062,
    payment_status: "paid",
    payment_method: "cash",
    paid_date: twoMonthsAgo,
    created_at: twoMonthsAgo + "T12:00:00Z",
    customers: { name: "Meena Kulkarni", phone: "9876500006", address: "34 Deccan Gymkhana, Pune" },
  },
  {
    id: "b6",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_id: "s6",
    bill_number: "BILL-20250325-0006",
    amount: 800,
    tax: 144,
    total: 944,
    payment_status: "paid",
    payment_method: "upi",
    paid_date: lastWeek,
    created_at: lastWeek + "T12:00:00Z",
    customers: { name: "Vikram Patel", phone: "9876500005", address: "88 Baner Road, Pune" },
  },
  {
    id: "b7",
    tenant_id: TENANT_ID,
    customer_id: "c9",
    service_id: "s7",
    bill_number: "BILL-20250310-0007",
    amount: 450,
    tax: 81,
    total: 531,
    payment_status: "paid",
    payment_method: "online",
    paid_date: lastMonth,
    created_at: lastMonth + "T12:00:00Z",
    customers: { name: "Rohit Deshpande", phone: "9876500009", address: "23 Viman Nagar, Pune" },
  },
  {
    id: "b8",
    tenant_id: TENANT_ID,
    customer_id: "c12",
    service_id: "s8",
    bill_number: "BILL-20250110-0008",
    amount: 1200,
    tax: 216,
    total: 1416,
    payment_status: "paid",
    payment_method: "cash",
    paid_date: threeMonthsAgo,
    created_at: threeMonthsAgo + "T12:00:00Z",
    customers: { name: "Kavita Bhosle", phone: "9876500012", address: "11 Hinjewadi Phase 1, Pune" },
  },
  {
    id: "b9",
    tenant_id: TENANT_ID,
    customer_id: "c7",
    service_id: "s9",
    bill_number: "BILL-20250312-0009",
    amount: 350,
    tax: 63,
    total: 413,
    payment_status: "paid",
    payment_method: "upi",
    paid_date: lastMonth,
    created_at: lastMonth + "T12:00:00Z",
    customers: { name: "Sanjay Gupta", phone: "9876500007", address: "56 Andheri West, Mumbai" },
  },

  // ===== RECENTLY PAID =====
  {
    id: "b10",
    tenant_id: TENANT_ID,
    customer_id: "c14",
    service_id: "s10",
    bill_number: "BILL-20250329-0010",
    amount: 550,
    tax: 99,
    total: 649,
    payment_status: "paid",
    payment_method: "cash",
    paid_date: twoDaysAgo,
    created_at: twoDaysAgo + "T12:00:00Z",
    customers: { name: "Pooja Sawant", phone: "9876500014", address: "32 Kothrud, Pune" },
  },
  {
    id: "b11",
    tenant_id: TENANT_ID,
    customer_id: "c11",
    service_id: "s11",
    bill_number: "BILL-20250328-0011",
    amount: 750,
    tax: 135,
    total: 885,
    payment_status: "paid",
    payment_method: "online",
    paid_date: threeDaysAgo,
    created_at: threeDaysAgo + "T12:00:00Z",
    customers: { name: "Deepak Nair", phone: "9876500011", address: "45 Dadar East, Mumbai" },
  },

  // ===== UNPAID BILLS =====
  {
    id: "b12",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_id: "s12",
    bill_number: "BILL-20250401-0012",
    amount: 600,
    tax: 108,
    total: 708,
    payment_status: "unpaid",
    payment_method: null,
    paid_date: null,
    created_at: today + "T12:00:00Z",
    customers: { name: "Priya Sharma", phone: "9876500002", address: "456 FC Road, Pune" },
  },
  {
    id: "b13",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_id: null,
    bill_number: "BILL-20250320-0013",
    amount: 400,
    tax: 72,
    total: 472,
    payment_status: "unpaid",
    payment_method: null,
    paid_date: null,
    created_at: lastWeek + "T12:00:00Z",
    customers: { name: "Amit Deshmukh", phone: "9876500003", address: "789 JM Road, Mumbai" },
  },
  {
    id: "b14",
    tenant_id: TENANT_ID,
    customer_id: "c8",
    service_id: null,
    bill_number: "BILL-20250315-0014",
    amount: 500,
    tax: 90,
    total: 590,
    payment_status: "unpaid",
    payment_method: null,
    paid_date: null,
    created_at: lastMonth + "T12:00:00Z",
    customers: { name: "Neha Reddy", phone: "9876500008", address: "90 Koregaon Park, Pune" },
  },
];

const bill_items = [
  // Bill b1 - Installation
  { id: "bi1", bill_id: "b1", description: "Kent Grand Plus Installation Kit", quantity: 1, unit_price: 1000, total: 1000 },
  { id: "bi2", bill_id: "b1", description: "Installation Service Charge", quantity: 1, unit_price: 500, total: 500 },

  // Bill b2 - Maintenance
  { id: "bi3", bill_id: "b2", description: "Sediment Filter", quantity: 1, unit_price: 250, total: 250 },
  { id: "bi4", bill_id: "b2", description: "Carbon Filter", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi5", bill_id: "b2", description: "Service Charge", quantity: 1, unit_price: 200, total: 200 },

  // Bill b3 - Installation
  { id: "bi6", bill_id: "b3", description: "Aquaguard Enhance Installation Kit", quantity: 1, unit_price: 800, total: 800 },
  { id: "bi7", bill_id: "b3", description: "Installation Charge", quantity: 1, unit_price: 400, total: 400 },

  // Bill b4 - Installation
  { id: "bi8", bill_id: "b4", description: "Pureit Ultima Installation Kit", quantity: 1, unit_price: 700, total: 700 },
  { id: "bi9", bill_id: "b4", description: "Installation Charge", quantity: 1, unit_price: 400, total: 400 },

  // Bill b5 - Filter Change
  { id: "bi10", bill_id: "b5", description: "RO Membrane", quantity: 1, unit_price: 500, total: 500 },
  { id: "bi11", bill_id: "b5", description: "Sediment Filter", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi12", bill_id: "b5", description: "Service Charge", quantity: 1, unit_price: 200, total: 200 },

  // Bill b6 - Repair
  { id: "bi13", bill_id: "b6", description: "Inlet Valve", quantity: 1, unit_price: 500, total: 500 },
  { id: "bi14", bill_id: "b6", description: "Labour Charge", quantity: 1, unit_price: 300, total: 300 },

  // Bill b7 - AMC
  { id: "bi15", bill_id: "b7", description: "Pre-Filter Candle", quantity: 2, unit_price: 125, total: 250 },
  { id: "bi16", bill_id: "b7", description: "AMC Service Charge", quantity: 1, unit_price: 200, total: 200 },

  // Bill b8 - Repair
  { id: "bi17", bill_id: "b8", description: "UV Lamp", quantity: 1, unit_price: 600, total: 600 },
  { id: "bi18", bill_id: "b8", description: "SMPS Board", quantity: 1, unit_price: 300, total: 300 },
  { id: "bi19", bill_id: "b8", description: "Labour Charge", quantity: 1, unit_price: 300, total: 300 },

  // Bill b9 - General Service
  { id: "bi20", bill_id: "b9", description: "General Service & Sanitization", quantity: 1, unit_price: 350, total: 350 },

  // Bill b10 - AMC
  { id: "bi21", bill_id: "b10", description: "Sediment Filter", quantity: 1, unit_price: 150, total: 150 },
  { id: "bi22", bill_id: "b10", description: "Carbon Block", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi23", bill_id: "b10", description: "AMC Service Charge", quantity: 1, unit_price: 200, total: 200 },

  // Bill b11 - Filter Change
  { id: "bi24", bill_id: "b11", description: "Sediment Filter", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi25", bill_id: "b11", description: "Carbon Filter", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi26", bill_id: "b11", description: "UF Membrane", quantity: 1, unit_price: 200, total: 200 },
  { id: "bi27", bill_id: "b11", description: "Service Charge", quantity: 1, unit_price: 150, total: 150 },

  // Bill b12 - Repair (unpaid)
  { id: "bi28", bill_id: "b12", description: "Estimated Repair Charge", quantity: 1, unit_price: 400, total: 400 },
  { id: "bi29", bill_id: "b12", description: "Inspection Fee", quantity: 1, unit_price: 200, total: 200 },

  // Bill b13 - Manual bill (unpaid)
  { id: "bi30", bill_id: "b13", description: "Spare Parts (pending delivery)", quantity: 1, unit_price: 250, total: 250 },
  { id: "bi31", bill_id: "b13", description: "Advance Service Charge", quantity: 1, unit_price: 150, total: 150 },

  // Bill b14 - Manual bill (unpaid)
  { id: "bi32", bill_id: "b14", description: "Initial Maintenance Package", quantity: 1, unit_price: 500, total: 500 },
];

const notifications = [
  {
    id: "n1",
    tenant_id: TENANT_ID,
    customer_id: "c4",
    service_id: "s15",
    type: "due_reminder",
    title: "Service Reminder",
    body: "Sneha Joshi - AMC service scheduled for tomorrow",
    sent_at: today + "T09:00:00Z",
    status: "sent",
  },
  {
    id: "n2",
    tenant_id: TENANT_ID,
    customer_id: "c10",
    service_id: "s16",
    type: "due_reminder",
    title: "Service Reminder",
    body: "Anjali Thakur - Maintenance scheduled for tomorrow",
    sent_at: today + "T09:00:00Z",
    status: "sent",
  },
  {
    id: "n3",
    tenant_id: TENANT_ID,
    customer_id: "c2",
    service_id: "s12",
    type: "due_reminder",
    title: "Service Today",
    body: "Priya Sharma - Repair service scheduled for today",
    sent_at: today + "T09:00:00Z",
    status: "sent",
  },
  {
    id: "n4",
    tenant_id: TENANT_ID,
    customer_id: "c3",
    service_id: "s20",
    type: "due_reminder",
    title: "Overdue Service",
    body: "Amit Deshmukh - Maintenance service is overdue!",
    sent_at: lastWeek + "T09:00:00Z",
    status: "sent",
  },
  {
    id: "n5",
    tenant_id: TENANT_ID,
    customer_id: "c1",
    service_id: "s21",
    type: "due_reminder",
    title: "Overdue Service",
    body: "Rajesh Kumar - Filter change is overdue!",
    sent_at: threeDaysAgo + "T09:00:00Z",
    status: "sent",
  },
  {
    id: "n6",
    tenant_id: TENANT_ID,
    customer_id: "c13",
    service_id: "s17",
    type: "due_reminder",
    title: "Installation Reminder",
    body: "Manish Tiwari - New Aquaguard Ritz installation day after tomorrow",
    sent_at: today + "T09:00:00Z",
    status: "failed",
  },
  {
    id: "n7",
    tenant_id: TENANT_ID,
    customer_id: "c5",
    service_id: "s22",
    type: "due_reminder",
    title: "Follow-up Reminder",
    body: "Vikram Patel - Follow-up on inlet valve repair next week",
    sent_at: today + "T09:00:00Z",
    status: "sent",
  },
];

module.exports = {
  TENANT_ID,
  USER_ID,
  tables: {
    tenants,
    users,
    customers,
    services,
    bills,
    bill_items,
    notifications,
  },
};
